name: Web Build + Deployment to GitHub Pages

on:
  # Trigger on push to specified branches or manually from the Actions tab
  push:
    branches:
      - master
      - main
  # Trigger on pull request events targeting specified branches
  pull_request:
    branches:
      - master
      - main
  # Allow manual execution from the Actions tab
  workflow_dispatch:

# Define concurrency settings
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.12.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Echo GitHub Repository Info
        run: |
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"

      - name: Flutter Build Web
        run: flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build-artifact
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
