name: Web Build + Deployment to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'  # Adjust version as per your project's requirement

      - name: Flutter Build Web
        run: |
          flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build-artifact
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
